
services:
  mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile
    container_name: mysql-container
    
    networks:
      - hello_network

  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: node-app
    depends_on:
      - mysql
    ports:
      - "3000:3000" # Map port 3000 on host to port 3000 in the container
    networks:
      - hello_network
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root_password
      DB_NAME: test
networks:
  hello_network:

volumes:
  mysql-data: